name: 'Deploy Databricks Workspace using Terraform'

on:
  pull_request:
    branches: [main]

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}    

jobs:
  terraform-databricks-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Terraform Init
      run: terraform init
      working-directory: ./dev
      
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./dev

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./dev

